"""Make nombre and apellido nullable to fix existing tests

Revision ID: a9e6081cc12d
Revises: c9293c9d51c5
Create Date: 2025-07-25 07:21:09.123456+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e6081cc12d'
down_revision: Union[str, Sequence[str], None] = 'c9293c9d51c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Make nombre and apellido nullable."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nombre',
               existing_type=sa.String(length=100),
               nullable=True,
               existing_comment='Nombre del usuario')
    op.alter_column('users', 'apellido',
               existing_type=sa.String(length=100),
               nullable=True,
               existing_comment='Apellido del usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Make nombre and apellido not nullable."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'apellido',
               existing_type=sa.String(length=100),
               nullable=False,
               existing_comment='Apellido del usuario')
    op.alter_column('users', 'nombre',
               existing_type=sa.String(length=100),
               nullable=False,
               existing_comment='Nombre del usuario')
    # ### end Alembic commands ###
