"""Add only pricing fields to Storage - manual

Revision ID: 0fdffd665886
Revises: dec0bbe60ba4
Create Date: 2025-07-29 18:35:15.308367+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdffd665886'
down_revision: Union[str, Sequence[str], None] = '817b44728e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storages', sa.Column('tarifa_mensual', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='Tarifa mensual del espacio de almacenamiento (COP)'))
    op.add_column('storages', sa.Column('tarifa_por_producto', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='Tarifa por producto almacenado (COP)'))
    op.create_check_constraint('ck_storage_tarifa_mensual_positive', 'storages', 'tarifa_mensual >= 0')
    op.create_check_constraint('ck_storage_tarifa_por_producto_positive', 'storages', 'tarifa_por_producto >= 0')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_storage_tarifa_por_producto_positive', 'storages', type_='check')
    op.drop_constraint('ck_storage_tarifa_mensual_positive', 'storages', type_='check')
    op.drop_column('storages', 'tarifa_por_producto')
    op.drop_column('storages', 'tarifa_mensual')
    # ### end Alembic commands ###