// ========================================
// CORE TYPES - Foundation for all other types
// ========================================
export type {
  EntityId,
  Timestamp,
  BaseEntity,
  CreateEntityRequest,
  UpdateEntityRequest,
  StandardResponse,
  PaginatedResponse,
  ListResponse,
  ApiError,
  ValidationError,
  EntityReference,
  UserReference,
  ProductReference,
  OrderReference,
  PartialEntity,
  CreateEntity,
  EntityWithoutTimestamps,
  EntityLookup,
  EntityCollection,
  LoadingState,
  AsyncState,
  EntityState,
} from './core.types';

export {
  isEntityId,
  isBaseEntity,
  isStandardResponse,
  isApiError,
} from './core.types';

// ========================================
// USER TYPES
// ========================================
export type {
  BaseUser,
  VendorProfile,
  UserContextState,
  VendorUpdateData,
} from './user.types';

// ========================================
// AUTHENTICATION TYPES
// ========================================
export { UserType } from './auth.types';
export type {
  User,
  LoginRequest,
  RegisterRequest,
  TokenResponse,
  UserInfoResponse,
  AuthResponse,
  PasswordResetRequest,
  PasswordResetConfirm,
  PasswordResetResponse,
  RefreshTokenRequest,
  OTPSendRequest,
  OTPVerifyRequest,
  OTPResponse,
  ApiError,
  UseAuthReturn,
  UseLoginReturn,
  UseRegisterReturn,
  UseLogoutReturn,
  LoginFormProps,
  RegisterFormProps,
} from './auth.types';
export type {
  AppTheme,
  Language,
  Currency,
  UIState,
  AppConfig,
  NotificationItem,
  AlertItem,
  AppState,
  AppActions,
  AppStoreType,
} from './app.types';
export type {
  Category,
  CategoryTree,
  CategoryFilter,
  CategoryBreadcrumb,
  CategoryStats,
  CreateCategoryRequest,
  UpdateCategoryRequest,
  CategoryListResponse,
  CategoryTreeResponse,
  CategoryTreeProps,
  CategoryManagerProps,
  CategorySelectorProps,
  CategoryBreadcrumbProps,
  CategoryFilterProps,
  CategoryState,
  CategoryActions,
  CategoryStore,
  CategoryError,
  DragItem,
  DropResult,
  CategorySearchParams,
  CategoryPagination,
} from './category.types';
export type {
  SearchType,
  ViewMode,
  SortOption,
  LoadingStates,
  SearchFilters,
  SearchTerm,
  SearchSuggestion,
  AutocompleteResult,
  SearchFacet,
  SearchFacetOption,
  PaginationMeta,
  SearchResult,
  SearchParams,
  SearchHistory,
  SavedSearch,
  SearchConfig,
  SearchError,
  SearchAnalytics,
  SearchState,
  SearchActions,
  UseSearchReturn,
  SearchComponentProps,
  SearchBarProps,
  SearchFiltersProps,
  SearchResultsProps,
  AdvancedSearchModalProps,
  SearchStore,
  FilterKey,
  SearchEventHandler,
  SearchEvent,
} from './search.types';
export type {
  UserType,
  User,
  LoginRequest,
  RegisterRequest,
  TokenResponse,
  AuthResponse,
  UserInfoResponse,
  PasswordResetRequest,
  PasswordResetConfirm,
  PasswordResetResponse,
  RefreshTokenRequest,
  OTPSendRequest,
  OTPVerifyRequest,
  OTPResponse,
  AuthState,
  AuthActions,
  AuthStore,
  ValidationError,
  LoginFormProps,
  RegisterFormProps,
  AuthGuardProps,
  AuthContextProps,
  UseAuthReturn,
  UseLoginReturn,
  UseRegisterReturn,
  UseLogoutReturn,
  AuthService,
  RequestInterceptorConfig,
  ResponseInterceptorConfig,
  AuthInterceptorConfig,
} from './auth.types';

// ========================================
// PRODUCT TYPES
// ========================================
export type {
  Product,
  ProductImage,
  ProductDimensions,
  ProductVariant,
  CreateProductRequest,
  UpdateProductRequest,
  ProductSearchRequest,
  ProductResponse,
  ProductListResponse,
  ProductSortField,
  ProductFilters,
  ProductSort,
  ProductState,
  ProductActions,
  ProductStore,
  ProductCardProps,
  ProductListProps,
  ProductFormProps,
  ProductFiltersProps,
  ProductPricing,
  ProductMetrics,
  ProductInventory,
} from './product.types';

// ========================================
// ORDER TYPES
// ========================================
export {
  OrderStatus,
  PaymentStatus,
  PaymentMethod,
} from './order.types';

export type {
  Order,
  OrderItem,
  ShippingAddress,
  BillingAddress,
  CreateOrderRequest,
  CreateOrderItemRequest,
  UpdateOrderRequest,
  OrderSearchRequest,
  OrderResponse,
  OrderListResponse,
  OrderSortField,
  OrderFilters,
  OrderSort,
  OrderState,
  OrderActions,
  OrderStore,
  OrderCardProps,
  OrderListProps,
  OrderDetailsProps,
  OrderStatusIndicatorProps,
  OrderFiltersProps,
  OrderSummary,
  OrderMetrics,
  OrderCommission,
} from './order.types';
